name: CI

on:
  push:

jobs:
  latex-paper:
    name: ğŸ“„ LaTeX paper
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Check-out
        uses: actions/checkout@v2
      - name: ğŸ—ï¸ Compile paper
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: paper
          root_file: touche22-axiomatic-reranking-query-reformulation.tex
  latex-talk:
    name: ğŸ“„ LaTeX talk
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Check-out
        uses: actions/checkout@v2
      - name: ğŸ—ï¸ Compile talk
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: talk
          root_file: talk.tex
  python-build:
    name: ğŸ—ï¸ Build Python wheels
    runs-on: ubuntu-latest
    env:
      SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL: True
    steps:
    - name: ğŸ“¥ Check-out
      uses: actions/checkout@v4
    - name: ğŸ§° Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: pip
        cache-dependency-path: pyproject.toml
    - name: ğŸ§° Install dependencies
      run: pip install build twine
    - name: ğŸ—ï¸ Build Python wheels
      run: python -m build
    - name: ğŸ§ª Check package bundles
      run: twine check dist/*
  python-code-format:
    name: ğŸ” Check Python code format
    runs-on: ubuntu-latest
    env:
      SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL: True
    steps:
    - name: ğŸ“¥ Check-out
      uses: actions/checkout@v4
    - name: ğŸ§° Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: pip
        cache-dependency-path: pyproject.toml
    - name: ğŸ§° Install dependencies
      run: pip install .[tests]
    - name: ğŸ” Check Python code format
      run: flake8
  python-lint:
    name: ğŸ” Lint Python code
    runs-on: ubuntu-latest
    env:
      SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL: True
    steps:
    - name: ğŸ“¥ Check-out
      uses: actions/checkout@v4
    - name: ğŸ§° Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: pip
        cache-dependency-path: pyproject.toml
    - name: ğŸ§° Install dependencies
      run: pip install .[tests]
    - name: ğŸ” Lint Python code
      run: pylint -E grimjack
  python-test:
    name: ğŸ§ª Test Python code
    runs-on: ubuntu-latest
    env:
      SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL: True
    steps:
    - name: ğŸ“¥ Check-out
      uses: actions/checkout@v4
    - name: ğŸ§° Install Protoc
      run: sudo apt install protobuf-compiler
    - name: ğŸ§° Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: pip
        cache-dependency-path: pyproject.toml
    - name: ğŸ§° Install dependencies
      run: pip install .[tests]
    - name: ğŸ§ª Test Python code
      run: pytest --cov --cov-report=term --cov-report=xml
    - name: ğŸ“¤ Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
  docker-build:
    name: ğŸ—ï¸ Docker build
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Check-out
        uses: actions/checkout@v2
      - name: ğŸ§° Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: ğŸ§° Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: ğŸ—ï¸ Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
