name: CI

on:
  push:

jobs:
  latex-paper:
    name: "ğŸ“„ LaTeX paper"
    runs-on: ubuntu-latest
    steps:
      - name: "ğŸ“¥ Check-out"
        uses: actions/checkout@v2
      - name: "ğŸ—ï¸ Compile paper"
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: paper
          root_file: touche22-axiomatic-reranking-query-reformulation.tex
      - name: "ğŸ“¤ Upload paper"
        uses: actions/upload-artifact@v2
        with:
          path: paper/touche22-axiomatic-reranking-query-reformulation.pdf
          name: latex-paper
  latex-talk:
    name: "ğŸ“„ LaTeX talk"
    runs-on: ubuntu-latest
    steps:
      - name: "ğŸ“¥ Check-out"
        uses: actions/checkout@v2
      - name: "ğŸ—ï¸ Compile talk"
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: talk
          root_file: talk.tex
      - name: "ğŸ“¤ Upload talk"
        uses: actions/upload-artifact@v2
        with:
          path: talk/talk.pdf
          name: latex-talk
  python-build:
    name: "ğŸ—ï¸ Build Python wheels"
    runs-on: ubuntu-latest
    env:
      SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL: True
    steps:
    - name: "ğŸ“¥ Check-out"
      uses: actions/checkout@v4
    - name: "ğŸ§° Install Python"
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: pip
        cache-dependency-path: pyproject.toml
    - name: "ğŸ§° Install dependencies"
      run: pip install build twine
    - name: "ğŸ—ï¸ Build Python wheels"
      run: python -m build
    - name: "ğŸ§ª Check package bundles"
      run: twine check dist/*
    - name: "ğŸ“¤ Upload Python wheels"
      uses: actions/upload-artifact@v4
      with:
        name: wheels
        path: dist
  python-code-format:
    name: "ğŸ” Check Python code format"
    runs-on: ubuntu-latest
    env:
      SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL: True
    steps:
    - name: "ğŸ“¥ Check-out"
      uses: actions/checkout@v4
    - name: "ğŸ§° Install Python"
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: pip
        cache-dependency-path: pyproject.toml
    - name: "ğŸ§° Install dependencies"
      run: pip install .[tests]
    - name: "ğŸ” Check Python code format"
      run: flake8 --exclude=./modern_talking/evaluation/track_1_kp_matching.py
  python-lint:
    name: "ğŸ” Lint Python code"
    runs-on: ubuntu-latest
    env:
      SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL: True
    steps:
    - name: "ğŸ“¥ Check-out"
      uses: actions/checkout@v4
    - name: "ğŸ§° Install Python"
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: pip
        cache-dependency-path: pyproject.toml
    - name: "ğŸ§° Install dependencies"
      run: pip install .[tests]
    - name: "ğŸ” Lint Python code"
      run: pylint -E modern_talking
  python-test:
    name: "ğŸ§ª Test Python code"
    runs-on: ubuntu-latest
    env:
      SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL: True
    steps:
    - name: "ğŸ“¥ Check-out"
      uses: actions/checkout@v4
    - name: "ğŸ§° Install Protoc"
      run: sudo apt install protobuf-compiler
    - name: "ğŸ§° Install Python"
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: pip
        cache-dependency-path: pyproject.toml
    - name: "ğŸ§° Install dependencies"
      run: pip install .[tests]
    - name: "ğŸ§ª Test Python code"
      run: pytest --cov --cov-report=term --cov-report=xml
    - name: "ğŸ“¤ Upload coverage to Codecov"
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
  docker-build:
    name: "ğŸ—ï¸ Docker build"
    runs-on: ubuntu-latest
    steps:
      - name: "ğŸ“¥ Check-out"
        uses: actions/checkout@v2
      - name: "ğŸ§° Set up QEMU"
        uses: docker/setup-qemu-action@v3
      - name: "ğŸ§° Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3
      - name: "ğŸ“„ Parse Docker metadata"
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository }}
      - name: "ğŸ—ï¸ Build Docker image"
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: "ğŸ—ï¸ Save Docker image"
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=docker,dest=image.tar
      - name: "ğŸ“¤ Upload Docker image"
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: actions/upload-artifact@v2
        with:
          path: image.tar
          name: docker-image
  release:
    name: "ğŸš€ Create GitHub release"
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs:
      - latex-paper
      - latex-talk
      - python-code-format
      - python-lint
      - python-unit-tests
      - docker-build
    runs-on: ubuntu-latest
    steps:
      - name: "ğŸ“¥ Check-out"
        uses: actions/checkout@v2
      - name: "ğŸ“¥ Download paper"
        uses: actions/download-artifact@v2
        with:
          path: touche22-axiomatic-reranking-query-reformulation.pdf
          name: latex-paper
      - name: "ğŸ“¥ Download talk"
        uses: actions/download-artifact@v2
        with:
          path: talk.pdf
          name: latex-talk
      - name: "ğŸ“¥ Download test coverage"
        uses: actions/download-artifact@v2
        with:
          path: coverage.xml
          name: python-test-coverage
      - name: "ğŸ“¥ Download Docker image"
        uses: actions/download-artifact@v2
        with:
          path: image.tar
          name: docker-image
      - name: "ğŸš€ Create GitHub release"
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.get-version.outputs.tag }}
          files: |
            touche22-axiomatic-reranking-query-reformulation.pdf
            talk.pdf
            coverage.xml
          fail_on_unmatched_files: true
          draft: false
          prerelease: false
          generate_release_notes: true
