name: Create release

on:
  push:
    tags: # Push events to new versions, e.g., 1.0, 20.15.10
      - "v[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+-*"
      - "v[0-9]+.[0-9]+.[0-9]+-*"

jobs:
  build-latex-paper:
    name: "ğŸ—ï¸ Build LaTeX paper"
    runs-on: ubuntu-20.04
    steps:
      - name: "ğŸ“¥ Check-out"
        uses: actions/checkout@v2
      - name: "ğŸ—ï¸ Compile paper"
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: paper
          root_file: sample-1col.tex
      - name: "ğŸ“¤ Upload paper"
        uses: actions/upload-artifact@v2
        with:
          path: paper/sample-1col.pdf
          name: Paper
  build-latex-talk:
    name: "ğŸ—ï¸ Build LaTeX talk"
    runs-on: ubuntu-20.04
    steps:
      - name: "ğŸ“¥ Check-out"
        uses: actions/checkout@v2
      - name: "ğŸ—ï¸ Compile talk"
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: talk
          root_file: talk.tex
      - name: "ğŸ“¤ Upload talk"
        uses: actions/upload-artifact@v2
        with:
          path: talk/talk.pdf
          name: Talk
  release:
    name: "ğŸš€ Release"
    runs-on: ubuntu-20.04
    needs:
      - build-latex-paper
      - build-latex-talk
    steps:
      - name: "ğŸ“¥ Check-out"
        uses: actions/checkout@v2
      - name: "ğŸ·ï¸ Get version tag"
        id: get-version
        run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}
      - name: "ğŸš€ Create GitHub release"
        id: create-github-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.get-version.outputs.tag }}
          prerelease: false
      - name: "ğŸ“¤ Upload paper"
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-github-release.outputs.upload_url }}
          asset_path: paper/sample-1col.pdf
          asset_name: sample-1col.pdf
          asset_content_type: application/pdf
      - name: "ğŸ“¤ Upload talk"
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-github-release.outputs.upload_url }}
          asset_path: talk/talk.pdf
          asset_name: talk.pdf
          asset_content_type: application/pdf
